export const products = [
  {
    id: '1',
    title: 'Amethyst Geode',
    description: 'Beautiful deep purple amethyst geode with natural formations. Perfect for collectors and crystal enthusiasts.',
    price: 129.99,
    category: 'Geodes',
    stock: 5,
    featured: true,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop',
  },
  {
    id: '2',
    title: 'Rose Quartz Crystal',
    description: 'Polished rose quartz stone, known as the stone of love and compassion. Ideal for meditation and healing.',
    price: 89.99,
    category: 'Crystals',
    stock: 10,
    featured: true,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop',
  },
  {
    id: '3',
    title: 'Black Tourmaline',
    description: 'Raw black tourmaline specimen with excellent protective properties. High quality mineral piece for collectors.',
    price: 149.99,
    category: 'Raw Minerals',
    stock: 8,
    featured: false,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop',
  },
  {
    id: '4',
    title: 'Citrine Cluster',
    description: 'Golden yellow citrine cluster. Associated with abundance and prosperity. Vibrant and radiant piece.',
    price: 199.99,
    category: 'Clusters',
    stock: 3,
    featured: true,
    image: 'https://images.unsplash.com/photo-1545821552-57569c4b1620?w=600&h=600&fit=crop',
  },
  {
    id: '5',
    title: 'Premium Ruby Gemstone',
    description: 'Exquisite deep red ruby with exceptional clarity and brilliance. Investment-grade gemstone from premium sources. This stunning ruby exhibits perfect faceting and vibrant coloration, making it a prized addition to any collection.',
    price: 449.99,
    category: 'Gemstones',
    stock: 2,
    featured: true,
    image: 'data:image/ruby-premium',
  },
  {
    id: '6',
    title: 'Smoky Quartz',
    description: 'Translucent smoky quartz crystal. Known for grounding energy and protection from negative thoughts.',
    price: 79.99,
    category: 'Crystals',
    stock: 12,
    featured: false,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop',
  },
  {
    id: '7',
    title: 'Selenite Wand',
    description: 'Pure white selenite wand, ideal for cleansing and clearing energy. Smooth and elegant piece.',
    price: 59.99,
    category: 'Wands',
    stock: 15,
    featured: false,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop',
  },
  {
    id: '8',
    title: 'Labradorite Stone',
    description: 'Labradorite with beautiful iridescent colors. Great for intuition and spiritual transformation.',
    price: 109.99,
    category: 'Polished Stones',
    stock: 7,
    featured: false,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop',
  },
  {
    id: '9',
    title: 'Clear Quartz Point',
    description: 'High quality clear quartz point, double terminated. Master healer crystal with excellent clarity.',
    price: 69.99,
    category: 'Points',
    stock: 20,
    featured: false,
    image: 'https://images.unsplash.com/photo-1545821552-57569c4b1620?w=600&h=600&fit=crop',
  },
];
